export const translations = {
  pt: {
    logout: 'Sair',
    login: 'Entrar', welcomeTitle: 'Gestão simples e segura de pessoas', welcomeDescription: 'Uma aplicação para consultar, organizar e importar registos de pessoas num único lugar.', welcomeFeatureRecords: 'Crie, consulte, edite e elimine registos.', welcomeFeatureImport: 'Importe dados em lote através de ficheiros CSV.', welcomeFeatureSecurity: 'Autenticação segura fornecida pelo Keycloak.', loginHint: 'Será redirecionado para o Keycloak para introduzir as suas credenciais.',
    language: 'Idioma', recordManagement: 'GESTÃO DE REGISTOS', people: 'Pessoas', subtitle: 'Consulte, organize e importe pessoas num único lugar.', lightMode: 'Modo claro', darkMode: 'Modo escuro', newPerson: 'Nova pessoa', editPerson: 'Editar pessoa', cancel: 'Cancelar', firstName: 'Primeiro nome', firstNameRequired: 'O primeiro nome é obrigatório.', lastName: 'Apelido', lastNameRequired: 'O apelido é obrigatório.', age: 'Idade', ageRequired: 'A idade deve ser superior a zero.', addressId: 'ID do endereço', optional: 'Opcional', saving: 'A guardar…', addPerson: 'Adicionar pessoa', saveChanges: 'Guardar alterações', importCsv: 'Importar CSV', csvHelp: 'Envie um ficheiro com as colunas', chooseCsv: 'Escolher ficheiro CSV', maxSize: 'Limite máximo de 10 MB', importing: 'A importar…', runImport: 'Executar importação', peopleList: 'Lista de pessoas', results: 'resultado(s)', search: 'Pesquisar pelo primeiro nome…', id: 'ID', name: 'Nome', address: 'Endereço', actions: 'Ações', loading: 'A carregar pessoas…', years: 'anos', edit: 'Editar', delete: 'Eliminar', empty: 'Nenhuma pessoa encontrada.', pagination: 'Paginação da lista de pessoas', showing: 'A mostrar', of: 'de', perPage: 'Por página', page: 'Página', previous: 'Página anterior', next: 'Página seguinte', created: 'Pessoa criada com sucesso.', updated: 'Pessoa atualizada com sucesso.', deleted: 'Pessoa eliminada com sucesso.', selectCsv: 'Selecione um ficheiro CSV.', importComplete: 'Importação concluída', saved: 'gravadas', ignored: 'ignoradas', read: 'lidas', errorDefault: 'Não foi possível concluir a operação.', deleteConfirm: 'Eliminar'
  },
  it: {
    logout: 'Esci',
    login: 'Accedi', welcomeTitle: 'Gestione delle persone semplice e sicura', welcomeDescription: 'Un’applicazione per consultare, organizzare e importare i dati delle persone in un unico posto.', welcomeFeatureRecords: 'Crea, consulta, modifica ed elimina i dati.', welcomeFeatureImport: 'Importa dati in blocco tramite file CSV.', welcomeFeatureSecurity: 'Autenticazione sicura fornita da Keycloak.', loginHint: 'Sarai reindirizzato a Keycloak per inserire le credenziali.',
    language: 'Lingua', recordManagement: 'GESTIONE DEI DATI', people: 'Persone', subtitle: 'Consulta, organizza e importa persone in un unico posto.', lightMode: 'Modalità chiara', darkMode: 'Modalità scura', newPerson: 'Nuova persona', editPerson: 'Modifica persona', cancel: 'Annulla', firstName: 'Nome', firstNameRequired: 'Il nome è obbligatorio.', lastName: 'Cognome', lastNameRequired: 'Il cognome è obbligatorio.', age: 'Età', ageRequired: "L'età deve essere maggiore di zero.", addressId: "ID dell'indirizzo", optional: 'Opzionale', saving: 'Salvataggio…', addPerson: 'Aggiungi persona', saveChanges: 'Salva modifiche', importCsv: 'Importa CSV', csvHelp: 'Invia un file con le colonne', chooseCsv: 'Scegli file CSV', maxSize: 'Dimensione massima 10 MB', importing: 'Importazione…', runImport: 'Avvia importazione', peopleList: 'Elenco persone', results: 'risultato/i', search: 'Cerca per nome…', id: 'ID', name: 'Nome', address: 'Indirizzo', actions: 'Azioni', loading: 'Caricamento persone…', years: 'anni', edit: 'Modifica', delete: 'Elimina', empty: 'Nessuna persona trovata.', pagination: "Paginazione dell'elenco persone", showing: 'Visualizzati', of: 'di', perPage: 'Per pagina', page: 'Pagina', previous: 'Pagina precedente', next: 'Pagina successiva', created: 'Persona creata con successo.', updated: 'Persona aggiornata con successo.', deleted: 'Persona eliminata con successo.', selectCsv: 'Seleziona un file CSV.', importComplete: 'Importazione completata', saved: 'salvate', ignored: 'ignorate', read: 'lette', errorDefault: "Impossibile completare l'operazione.", deleteConfirm: 'Eliminare'
  },
  es: {
    logout: 'Salir',
    login: 'Entrar', welcomeTitle: 'Gestión de personas sencilla y segura', welcomeDescription: 'Una aplicación para consultar, organizar e importar registros de personas en un solo lugar.', welcomeFeatureRecords: 'Cree, consulte, edite y elimine registros.', welcomeFeatureImport: 'Importe datos en lote mediante archivos CSV.', welcomeFeatureSecurity: 'Autenticación segura proporcionada por Keycloak.', loginHint: 'Será redirigido a Keycloak para introducir sus credenciales.',
    language: 'Idioma', recordManagement: 'GESTIÓN DE REGISTROS', people: 'Personas', subtitle: 'Consulta, organiza e importa personas en un solo lugar.', lightMode: 'Modo claro', darkMode: 'Modo oscuro', newPerson: 'Nueva persona', editPerson: 'Editar persona', cancel: 'Cancelar', firstName: 'Nombre', firstNameRequired: 'El nombre es obligatorio.', lastName: 'Apellido', lastNameRequired: 'El apellido es obligatorio.', age: 'Edad', ageRequired: 'La edad debe ser superior a cero.', addressId: 'ID de la dirección', optional: 'Opcional', saving: 'Guardando…', addPerson: 'Añadir persona', saveChanges: 'Guardar cambios', importCsv: 'Importar CSV', csvHelp: 'Envíe un archivo con las columnas', chooseCsv: 'Elegir archivo CSV', maxSize: 'Tamaño máximo de 10 MB', importing: 'Importando…', runImport: 'Ejecutar importación', peopleList: 'Lista de personas', results: 'resultado(s)', search: 'Buscar por nombre…', id: 'ID', name: 'Nombre', address: 'Dirección', actions: 'Acciones', loading: 'Cargando personas…', years: 'años', edit: 'Editar', delete: 'Eliminar', empty: 'No se encontraron personas.', pagination: 'Paginación de la lista de personas', showing: 'Mostrando', of: 'de', perPage: 'Por página', page: 'Página', previous: 'Página anterior', next: 'Página siguiente', created: 'Persona creada correctamente.', updated: 'Persona actualizada correctamente.', deleted: 'Persona eliminada correctamente.', selectCsv: 'Seleccione un archivo CSV.', importComplete: 'Importación completada', saved: 'guardadas', ignored: 'ignoradas', read: 'leídas', errorDefault: 'No se pudo completar la operación.', deleteConfirm: 'Eliminar'
  },
  en: {
    logout: 'Sign out',
    login: 'Sign in', welcomeTitle: 'Simple and secure people management', welcomeDescription: 'An application to view, organize and import people records in one place.', welcomeFeatureRecords: 'Create, view, edit and delete records.', welcomeFeatureImport: 'Import data in bulk using CSV files.', welcomeFeatureSecurity: 'Secure authentication provided by Keycloak.', loginHint: 'You will be redirected to Keycloak to enter your credentials.',
    language: 'Language', recordManagement: 'RECORD MANAGEMENT', people: 'People', subtitle: 'View, organize and import people in one place.', lightMode: 'Light mode', darkMode: 'Dark mode', newPerson: 'New person', editPerson: 'Edit person', cancel: 'Cancel', firstName: 'First name', firstNameRequired: 'First name is required.', lastName: 'Last name', lastNameRequired: 'Last name is required.', age: 'Age', ageRequired: 'Age must be greater than zero.', addressId: 'Address ID', optional: 'Optional', saving: 'Saving…', addPerson: 'Add person', saveChanges: 'Save changes', importCsv: 'Import CSV', csvHelp: 'Upload a file with the columns', chooseCsv: 'Choose CSV file', maxSize: 'Maximum size 10 MB', importing: 'Importing…', runImport: 'Run import', peopleList: 'People list', results: 'result(s)', search: 'Search by first name…', id: 'ID', name: 'Name', address: 'Address', actions: 'Actions', loading: 'Loading people…', years: 'years', edit: 'Edit', delete: 'Delete', empty: 'No people found.', pagination: 'People list pagination', showing: 'Showing', of: 'of', perPage: 'Per page', page: 'Page', previous: 'Previous page', next: 'Next page', created: 'Person created successfully.', updated: 'Person updated successfully.', deleted: 'Person deleted successfully.', selectCsv: 'Select a CSV file.', importComplete: 'Import completed', saved: 'saved', ignored: 'ignored', read: 'read', errorDefault: 'The operation could not be completed.', deleteConfirm: 'Delete'
  },
  fr: {
    logout: 'Déconnexion',
    login: 'Connexion', welcomeTitle: 'Gestion des personnes simple et sécurisée', welcomeDescription: 'Une application pour consulter, organiser et importer les dossiers des personnes en un seul endroit.', welcomeFeatureRecords: 'Créez, consultez, modifiez et supprimez des dossiers.', welcomeFeatureImport: 'Importez des données en masse avec des fichiers CSV.', welcomeFeatureSecurity: 'Authentification sécurisée fournie par Keycloak.', loginHint: 'Vous serez redirigé vers Keycloak pour saisir vos identifiants.',
    language: 'Langue', recordManagement: 'GESTION DES DOSSIERS', people: 'Personnes', subtitle: 'Consultez, organisez et importez des personnes en un seul endroit.', lightMode: 'Mode clair', darkMode: 'Mode sombre', newPerson: 'Nouvelle personne', editPerson: 'Modifier la personne', cancel: 'Annuler', firstName: 'Prénom', firstNameRequired: 'Le prénom est obligatoire.', lastName: 'Nom', lastNameRequired: 'Le nom est obligatoire.', age: 'Âge', ageRequired: "L'âge doit être supérieur à zéro.", addressId: "ID de l'adresse", optional: 'Facultatif', saving: 'Enregistrement…', addPerson: 'Ajouter une personne', saveChanges: 'Enregistrer', importCsv: 'Importer un CSV', csvHelp: 'Envoyez un fichier avec les colonnes', chooseCsv: 'Choisir un fichier CSV', maxSize: 'Taille maximale de 10 Mo', importing: 'Importation…', runImport: "Lancer l'importation", peopleList: 'Liste des personnes', results: 'résultat(s)', search: 'Rechercher par prénom…', id: 'ID', name: 'Nom', address: 'Adresse', actions: 'Actions', loading: 'Chargement des personnes…', years: 'ans', edit: 'Modifier', delete: 'Supprimer', empty: 'Aucune personne trouvée.', pagination: 'Pagination de la liste des personnes', showing: 'Affichage de', of: 'sur', perPage: 'Par page', page: 'Page', previous: 'Page précédente', next: 'Page suivante', created: 'Personne créée avec succès.', updated: 'Personne mise à jour avec succès.', deleted: 'Personne supprimée avec succès.', selectCsv: 'Sélectionnez un fichier CSV.', importComplete: 'Importation terminée', saved: 'enregistrées', ignored: 'ignorées', read: 'lues', errorDefault: "Impossible de terminer l'opération.", deleteConfirm: 'Supprimer'
  },
  de: {
    logout: 'Abmelden',
    login: 'Anmelden', welcomeTitle: 'Einfache und sichere Personenverwaltung', welcomeDescription: 'Eine Anwendung zum Anzeigen, Organisieren und Importieren von Personendaten an einem Ort.', welcomeFeatureRecords: 'Datensätze erstellen, anzeigen, bearbeiten und löschen.', welcomeFeatureImport: 'Daten gesammelt über CSV-Dateien importieren.', welcomeFeatureSecurity: 'Sichere Authentifizierung durch Keycloak.', loginHint: 'Sie werden zur Eingabe Ihrer Anmeldedaten zu Keycloak weitergeleitet.',
    language: 'Sprache', recordManagement: 'DATENVERWALTUNG', people: 'Personen', subtitle: 'Personen an einem Ort anzeigen, verwalten und importieren.', lightMode: 'Heller Modus', darkMode: 'Dunkler Modus', newPerson: 'Neue Person', editPerson: 'Person bearbeiten', cancel: 'Abbrechen', firstName: 'Vorname', firstNameRequired: 'Der Vorname ist erforderlich.', lastName: 'Nachname', lastNameRequired: 'Der Nachname ist erforderlich.', age: 'Alter', ageRequired: 'Das Alter muss größer als null sein.', addressId: 'Adress-ID', optional: 'Optional', saving: 'Speichern…', addPerson: 'Person hinzufügen', saveChanges: 'Änderungen speichern', importCsv: 'CSV importieren', csvHelp: 'Datei mit folgenden Spalten hochladen', chooseCsv: 'CSV-Datei auswählen', maxSize: 'Maximale Größe 10 MB', importing: 'Importieren…', runImport: 'Import starten', peopleList: 'Personenliste', results: 'Ergebnis(se)', search: 'Nach Vornamen suchen…', id: 'ID', name: 'Name', address: 'Adresse', actions: 'Aktionen', loading: 'Personen werden geladen…', years: 'Jahre', edit: 'Bearbeiten', delete: 'Löschen', empty: 'Keine Personen gefunden.', pagination: 'Seitennavigation der Personenliste', showing: 'Anzeige', of: 'von', perPage: 'Pro Seite', page: 'Seite', previous: 'Vorherige Seite', next: 'Nächste Seite', created: 'Person erfolgreich erstellt.', updated: 'Person erfolgreich aktualisiert.', deleted: 'Person erfolgreich gelöscht.', selectCsv: 'Wählen Sie eine CSV-Datei aus.', importComplete: 'Import abgeschlossen', saved: 'gespeichert', ignored: 'ignoriert', read: 'gelesen', errorDefault: 'Der Vorgang konnte nicht abgeschlossen werden.', deleteConfirm: 'Löschen'
  }
} as const;

export type Language = keyof typeof translations;
